# Generated by Django 4.0 on 2023-03-17 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 3, 17, 11, 40, 25, 670188, tzinfo=utc), verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 3, 17, 11, 40, 25, 670323, tzinfo=utc), verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='タグ')),
            ],
        ),
    ]
